# Generated by Django 4.2.10 on 2024-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.TextField(choices=[('Clothes Topic', 'Clothes'), ('Equipment Topic', 'Equipment'), ('Courses Topic', 'Courses'), ('Other Topic', 'Other')])),
                ('timeframe', models.TextField(choices=[('Days Timeframe', 'Within days'), ('Weeks Timeframe', 'Within weeks'), ('Months Timeframe', 'Within a few months'), ('Year Timeframe', 'In a year'), ('Unsure Timefram', 'Unsure')])),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
