# Generated by Django 4.2.10 on 2024-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='timeframe',
            field=models.TextField(blank=True, choices=[('Days Timeframe', 'Within days'), ('Weeks Timeframe', 'Within weeks'), ('Months Timeframe', 'Within a few months'), ('Year Timeframe', 'In a year'), ('Unsure Timefram', 'Unsure')], null=True),
        ),
    ]
