# Generated by Django 4.2.10 on 2024-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactrequest_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(max_length=900),
        ),
    ]
