# Generated by Django 4.2.10 on 2024-05-31 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(max_length=900, validators=[django.core.validators.MinLengthValidator(30, 'Message must be at least 30 characters')]),
        ),
    ]
