# Generated by Django 4.2.10 on 2024-04-26 21:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_productrating_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='star',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=400, validators=[django.core.validators.MinLengthValidator(40, 'Review must be greater than 40 characters')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
