# Generated by Django 4.2.10 on 2024-04-27 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_star_options_star_body_star_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='body',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(30, 'Review must be greater than 30 characters')]),
        ),
        migrations.AlterField(
            model_name='star',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Rating must be at least 1'), django.core.validators.MaxValueValidator(5, 'Rating must be a max of 5')]),
        ),
    ]
