# Generated by Django 4.2.10 on 2024-05-31 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_star_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='body',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(30, 'Review must be at least 30 characters')]),
        ),
    ]
